eureka:
  instance:
    hostname: config-service
  client:
    service-url:
      defaultZone: http://discovery-service:8080/eureka
spring:
  cloud:
    config:
      override.system-properties: false

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info
    endpoint:
      health:
        show-details: always
