spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:${POSTGRESQL_PORT}/auth
    username: ${POSTGRESQL_LOGIN}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpiration: ${JWT_EXPIRATION}
  refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION}
  encryptionSecret: ${ENCRYPTION_SECRET}

springdoc:
  swagger-ui:
    path: "/api/v1/auth/swagger-ui.html"
  api-docs:
    path: "/api/v1/auth/v3/api-docs"