spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/developer
    username: dima
    password: dima
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8010