spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: developer-service
          uri: http://developer-service:8080
          predicates:
            - Path=/api/v1/developers/**
        - id: project-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/projects/**
        - id: project-assignment-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/project-assignments/**
        - id: task-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/tasks/**
        - id: task-assignment-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/task-assignments/**

