spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: developer-service
          uri: lb:http://DEVELOPER-SERVICE
          predicates:
            - Path=/api/v1/developers/**
        - id: project-service
          uri: lb:http://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/projects/**
        - id: project-assignment-service
          uri: lb:http://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/project-assignments/**
        - id: task-service
          uri: lb:http://TASK-SERVICE
          predicates:
            - Path=/api/v1/tasks/**
        - id: task-assignment-service
          uri: lb:http://TASK-SERVICE
          predicates:
            - Path=/api/v1/task-assignments/**
server:
  port: 8222

