spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-project-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/admin/projects/**
          filters:
            - JwtAuthenticationFilter

        - id: user-project-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/user/projects/**
          filters:
            - JwtAuthenticationFilter

        - id: project-assignment-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/project-assignments/**
          filters:
            - JwtAuthenticationFilter

        - id: doc-project-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/doc/projects/**
          filters:
            - JwtAuthenticationFilter



        - id: admin-task-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/admin/tasks/**
          filters:
            - JwtAuthenticationFilter

        - id: user-task-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/user/tasks/**
          filters:
            - JwtAuthenticationFilter

        - id: doc-task-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/doc/tasks/**
          filters:
            - JwtAuthenticationFilter


        - id: task-assignment-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/task-assignments/**
          filters:
            - JwtAuthenticationFilter




        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - JwtAuthenticationFilter

        - id: doc-auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/doc/auth/**
          filters:
            - JwtAuthenticationFilter

        - id: admin-user-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/admin/users/**
          filters:
            - JwtAuthenticationFilter

        - id: all-user-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/all/users/**
          filters:
            - JwtAuthenticationFilter

app:
  jwtSecret: ${JWT_SECRET}
  auth-url: http://auth-service:8080/api/v1/auth
  user-url: http://auth-service:8080/api/v1/admin/users


