spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: developer-service
          uri: http://developer-service:8080
          predicates:
            - Path=/api/v1/developers/**
          filters:
            - JwtAuthenticationFilter

        - id: project-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/projects/**
          filters:
            - JwtAuthenticationFilter

        - id: project-assignment-service
          uri: http://project-service:8080
          predicates:
            - Path=/api/v1/project-assignments/**
          filters:
            - JwtAuthenticationFilter

        - id: task-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - JwtAuthenticationFilter

        - id: task-assignment-service
          uri: http://task-service:8080
          predicates:
            - Path=/api/v1/task-assignments/**
          filters:
            - JwtAuthenticationFilter

        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - JwtAuthenticationFilter

app:
  jwtSecret: ${JWT_SECRET}
  auth-url: http://auth-service:8080/api/v1/auth


