spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:${POSTGRESQL_PORT}/project
    username: ${POSTGRESQL_LOGIN}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: projectNotification:com.example.project.kafka.ProjectNotification

application:
  config:
    developer-url: http://developer-service:8080/api/v1/developers
    task-url: http://task-service:8080/api/v1/tasks
    task-assignment-url: http://task-service:8080/api/v1/task-assignments

springdoc:
  swagger-ui:
    path: "/api/v1/projects/swagger-ui.html"
  api-docs:
    path: "/api/v1/projects/v3/api-docs"