spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:${POSTGRESQL_PORT}/task
    username: ${POSTGRESQL_LOGIN}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: taskNotification:com.example.task.kafka.TaskNotification,taskChangedStateNotification:com.example.task.kafka.TaskChangedStateNotification

application:
  config:
    developer-url: http://developer-service:8080/api/v1/developers
    project-url: http://project-service:8080/api/v1/projects

springdoc:
  swagger-ui:
    path: "/api/v1/tasks/swagger-ui.html"
  api-docs:
    path: "/api/v1/tasks/v3/api-docs"